### PR TITLE
Removed file size check, Parse Android SDK

### PR DESCRIPTION
**Pull request by kristoprifti**

### CODE REVIEW

**Comment by kristoprifti** [comment]
@grantland i did a new PR if it is not a problem. Can you please check this one ? everything is in one commit this time

**Comment by facebook-github-bot-1** [comment]
By analyzing the blame information on this pull request, we identified @daisuke-nomura and @wangmengyan95 to be potential reviewers.

**Comment by grantland** [comment]
Looks good! Merging

Fixes #453

**Comment by kristoprifti** [comment]
@grantland how can i apply these changes to my project ? bcs the 1.13 version is still the same, Will you guys release a new version or smth ?

**Comment by kristoprifti** [comment]
@grantland Hello. I wanted to ask about the next milestone release date since we have our app in production and we would really appreciate an update :)

**Comment by grantland** [comment]
No planned date at the moment, but currently waiting on two more changes: https://github.com/ParsePlatform/Parse-SDK-Android/milestones/1.13.1

**Comment by kristoprifti** [comment]
@grantland can you set up a due date for the latest milestone ? as i mentioned before, we have our app in production and we really need to update our Parse library for Android. Can we move the unresolved issue to another milestone and release the current one ?

**Comment by grantland** [comment]
Done, currently set to Wednesday.

**Comment by kristoprifti** [comment]
@grantland when will the milestone be published so we can use it ? Do we need to do something in our side ?

**Comment by grantland** [comment]
I just pushed it. You'll need to target the latest version and let it filter throughout the Maven repository.

**Comment by munl** [comment]
Hi has this code been pushed yet?  I'm using:
compile 'com.parse:parse-android:1.+' 
to compile parse, but I'm still getting the "java.lang.IllegalArgumentException: ParseFile must be less than 10485760 bytes"  exception

**Comment by kristoprifti** [comment]
@munl you need to use 1.13.1 version of Parse. This code has been pushed long time ago and i personally dont get this problem anymore :)

**Comment by thphuc** [comment]
@kristoprifti I am using 1.13.1 but still getting the exception. Do you have any hint?

**Comment by kristoprifti** [comment]
@thphuc these are the changes i did to remove the file size check and this is applied in 1.13.1. Please double check with ParseFile.java in your project if it still contains the lines i removed. Otherwise if the problem still persists you can download the version 1.13.0 as a separate project and include it as a dependency, then you can make the changes I did manually and you can also debug further when you get the exception :) i hope it helps!

https://github.com/ParsePlatform/Parse-SDK-Android/pull/462/files

**Pull request merged**
