### PR TITLE
Feature/google auth helpers

### PR DESCRIPTION
**Pull request by makar15**

### CODE REVIEW

**Comment by facebook-github-bot-6** [comment]
By analyzing the blame information on this pull request, we identified @richardjrossiii, @wangmengyan95 and @rogerhu to be potential reviewers.

**Comment by facebook-github-bot-6** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-9** [comment]
@makar15 updated the pull request.

**Comment by facebook-github-bot-6** [comment]
@makar15 updated the pull request.

**Comment by grantland** [comment]
Thanks for putting in the work to create this, however, we won't be merging this in. The current pattern to follow is to create a separate library that depends on `Parse-SDK-Android`, similar to https://github.com/ParsePlatform/ParseTwitterUtils-Android and https://github.com/ParsePlatform/ParseFacebookUtils-Android

**Pull request closed without merging**
