### PR TITLE
Add ProGuard section to README

### PR DESCRIPTION
**Pull request by hermanliang**

### CODE REVIEW

**Comment by rogerhu** [comment]
I'd just add it here:

https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/release-proguard.pro

**Comment by hermanliang** [comment]
It seems necessary when installing SDK in gradle

```groovy
android {
    ...
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
  ...
  compile 'com.parse:parse-android:1.14.1'
}
```

then run
```
./gradlew assembleRelease
```

BUILD FAILED unless I add the rule

**Comment by rogerhu** [comment]
Correct but adding it the proguard file should include it with the lib

https://github.com/codepath/android_guides/wiki/Building-your-own-Android-library#using-with-proguard

**Comment by hermanliang** [comment]
Does it due to SDK release jar not aar?

**Comment by rogerhu** [comment]
We release both.  There is already a ProGuard file though...Are you saying it gets ignored for you if you were to add this line and use jetpack.io to confirm?

**Comment by Jawnnypoo** [comment]
Yeah, this is probably needed now, since we have a hard dependency now on OkHttp

https://github.com/square/okhttp#proguard

**Comment by rogerhu** [comment]
I understand that part the question is whether we can just add it to https://github.com/ParsePlatform/Parse-SDK-Android/blob/master/Parse/release-proguard.pro.

Otherwise we should update the docs to include all the ProGuard lines listed there.

**Comment by Jawnnypoo** [comment]
Ah yeah, my bad. Yes, we can just add it there, should fix the issue.

**Comment by rogerhu** [comment]
I guess the one thing you have to do is use @aar in order to include the ProGuard lines 

```
compile 'com.parse:parse-android:1.14.1@aar'
```

**Comment by Jawnnypoo** [comment]
@rogerhu Interesting, might be worth adding that as the instruction in the README instead then

**Comment by rogerhu** [comment]
Yep, we should point people to the ProGuard config if they need to manually use it.

Do people still use non-JARs?  What if we made the packaging type AAR by default as well?

**Comment by Jawnnypoo** [comment]
I am all for that, I see no reason to have it build a jar by default, as it is an Android library, not a Java library.

**Comment by rogerhu** [comment]
https://github.com/ParsePlatform/Parse-SDK-Android/pull/621

**Comment by rogerhu** [comment]
To be clear we build both jar and aar.  The change just causes the pom XML file to tell Gradle to use the war version.

 Gradle in the past has difficulties with transient dependencies (I.e. okhttp depends on okio) with aar so I hope this is the only change necessary and we don't also need to use transient=true too

**Comment by hermanliang** [comment]
Thanks to @rogerhu @Jawnnypoo 
This issue should be resolved by #621. 
I think we can close this PR.

**Pull request closed without merging**
