### PR TITLE
Removed ParseFile size limitation

### LINKED ISSUE #453: Remove ParseFile 10Mb limitation
Hey guys, we migrated to Parse Server and on iOS we can now use files larger than 10Mb. On Android however, we can't even create a file larger than 10Mb. We get this error when we run 

ParseFile video1 = new ParseFile("answer_1.mp4", video1ByteArray);

FATAL EXCEPTION: main Process: com.terre.android.terremoto, PID: 7919
                 java.lang.IllegalArgumentException: ParseFile must be less than 10485760 bytes

Our Parse Server supports files larger than 10Mb and on iOS everything works fine.

Is there anything we can do?

### PR DESCRIPTION
**Pull request by kristoprifti**
Removed the limitation for the ParseFile in Android SDK to be in sync
with iOS SDK

Fixes #453

### CODE REVIEW

**Comment by facebook-github-bot-4** [comment]
By analyzing the blame information on this pull request, we identified @daisuke-nomura and @wangmengyan95 to be potential reviewers.

**Comment by facebook-github-bot-0** [comment]
@kristoprifti updated the pull request.

**Comment by kristoprifti** [comment]
@grantland can you please take a look at my commit ? i just removed the file check and also the corresponding test for it and i seem to get an error in the codecov and i am not familiar on how to check my error. thank you

**Comment by grantland** [comment]
The codecov error here can be ignored, since we've removed code and shouldn't have made the code coverage worse.

The code changes look good, would you mind squashing your commits and I can merge?

**Comment by kristoprifti** [comment]
@grantland can you please check now ? i squashed my commits in one. Can you do the merging ?

**Comment by grantland** [comment]
It seems that there are still 2 commits, are you sure you updated the PR?

**Comment by facebook-github-bot-1** [comment]
@kristoprifti updated the pull request.

**Pull request closed without merging**
