### PR TITLE
Fix signUp and linkWith with an anonymous user

### PR DESCRIPTION
**Pull request by grantland**
Fixes integration test failures caused by #52

We strip anonymity in `signUp` and `linkWith` before calling into
`saveAsync` where there's a fork in logic for `isLazy()`. Since we now
determine `isLazy()` based off `objectId != null &&
ParseAnonymousUtils.isLinked(this)`,
`isLazy()` returns the incorrect value for these logic paths.

The solution is to get the value of `isLazy()` before stripping anonymity
and passing it through to `saveAsync()`.

* Callers of resolveLazinessAsync never use it's return value, might as well make it `Void`
* Make signUp more robust by reverting current user's password on failure if that's how it originally was
* Make signUp more robust by reverting the current user's password on success

### CODE REVIEW

**Comment by grantland** [comment]
Still writing a unit test that will simulate this behavior for the future.

/cc @lukas1994 @hallucinogen

**Comment by grantland** [comment]
So it doesn't seem like there's a good way to write a unit test as the scenario is more of a integration test scenario, especially since I added `saveAsync(sessionToken, isLazy, toAwait)`.

**Comment by lukas1994** [comment]
LGTM
Do we have integration tests for this?

**Comment by hallucinogen** [comment]
So this is basically the same as our initial behavior, except `isLazy` is being injected into `saveAsync`?

**Comment by grantland** [comment]
@lukas1994 yeah we have integration tests for this. they're currently failing and this makes them pass

@hallucinogen pretty much

**Comment by hallucinogen** [comment]
Sounds good then.

**Pull request merged**
