### PR TITLE
Parcelable implementation for ParseFile

### PR DESCRIPTION
**Pull request by johncordeiro**
This is the implementation of Parcelable interface on ParseFile for remote and local files. It's very useful to pass complex objects through activities, specially when you are using Parse with delegated properties in Kotlin.

### CODE REVIEW

**Comment by johncordeiro** [comment]
Is there anyone maintaining this project?

**Comment by rogerhu** [comment]
+1

**Comment by rogerhu** [comment]
Can you simply extend the class instead of needing to put in on ParseFile?

**Comment by rogerhu** [comment]
Does anyone else have any opinions about the need to do this?

**Comment by natario1** [comment]
I don’t think that parceling a whole file with its byte array would be considered good practice. I also remember Parcel (or Bundle) throwing when its contents are too large.

In my opinion this should work only when the file is backed by an url, and if not (e.g. ParseFile not saved yet) throw an exception. That would be harmless and a good step in the direction of implementing Parcelable in the SDK.

**Comment by rogerhu** [comment]
Yeah there is a Parcelable max size of 1 Mb (https://developer.android.com/reference/android/os/TransactionTooLargeException.html) 

Going to close unless there is a revision to it.

**Comment by johncordeiro** [comment]
Yes, it seems to be reasonable, the code was updated.

**Comment by rogerhu** [comment]
See https://github.com/ParsePlatform/Parse-SDK-Android/issues/122

**Comment by johncordeiro** [comment]
@rogerhu #122 is another step after ParseFile implementation, because ParseFile is not a ParseObject. We could handle them separately.

**Pull request closed without merging**
