### PR TITLE
setColor for Notifications on Lollipop+

### PR DESCRIPTION
**Pull request by mars3142**
It's the pull request for the issue #162

### CODE REVIEW

**Comment by mars3142** [comment]
The two changed classes hadn't any tests previously. Do you need tests for this?

**Comment by grantland** [comment]
Thanks for the PR, however, this seems to be something that can easily be accomplished without modifying the SDK by extending `ParsePushBroadcastReceiver#getNotification()` on a per-app basis which is recommended in our guide.

**Comment by robertdolca** [comment]
This feature would be very useful. Overwriting the whole #getNotification() only for changing the background color seems like a bad practice.

**Comment by mars3142** [comment]
Thanks, @robertdolca - This was my intention.

**Pull request closed without merging**
