### PR TITLE
Made ParseOperationSet thread-safe.

### PR DESCRIPTION
**Pull request by lukas1994**
See: https://github.com/ParsePlatform/Parse-SDK-Android/issues/76

### CODE REVIEW

**Comment by hallucinogen** [comment]
Not sure this is the correct solution to #76. `ParseOperationSet` docs mentioned that `ParseOperationSet` is not thread-safe so we can enforce thread-safety (and thus, atomicity) from its usage while keeping `ParseOperationSet` data structure fast and simple.

Imagine this scenario
1. Make an object: `obj.put("corgi", "awesome")`. It will create `ParseSetOperation { "corgi" => "awesome" }`
2. `obj.saveInBackground()`. It will pass the `operationSet` to `NetworkObjectController`.
3. Somehow (this is the one that I'm not sure of) mutate the `operationSet` from another thread: `ParseSetOperation { "corgi" => "cute" }`
4. Save finish.

The expected result is to have an object saved with `obj.get("corgi")` equals to `"awesome"` but in this case it will return `"cute"`. This PR will make sure that `ParseOperationSet` will never be in invalid state (i.e. in the middle of mutation), which is great. But it doesn't answer the possible race condition problem.

So the question is more: is the race condition possible to begin with? If it isn't, then we don't have to change anything. If it's, then that `ParseOperationSet` **usage** is what we need to fix, not the `ParseOperationSet` itself.

**Comment by lukas1994** [comment]
OK I'll check all places where ```ParseOperationSet``` is used.

**Comment by lukas1994** [comment]
I checked all places where ```ParseOperationSet``` is used and couldn't find any concurrency issues.
The scenario you described above can't happen because if ```save()``` gets called a new ```ParseOperationSet``` gets enqueued (to ```operationSetQueue```) and all methods mutate the top of the queue.

**Comment by lukas1994** [comment]
It doesn't make sense to make the ```ParseOperationSet``` thread-safe, the synchronization will just decrease efficiency.

**Pull request closed without merging**
