### PR TITLE
Fix bug in ParseOkHttpClient

### PR DESCRIPTION
**Pull request by ly85206559**
ClassCastException happened while delete ParseObject

### CODE REVIEW

**Comment by grantland** [comment]
Could you provide more context on the bug you're fixing? Possibly a stack trace or an issue with more information?

**Comment by ly85206559** [comment]
: java.lang.ClassCastException: okhttp3.RequestBody$2 cannot be cast to com.parse.ParseOkHttpClient$ParseOkHttpRequestBody
at com.parse.ParseOkHttpClient.getParseHttpRequest(ParseOkHttpClient.java:193) 
at com.parse.ParseOkHttpClient.access$000(ParseOkHttpClient.java:39)
at com.parse.ParseOkHttpClient$1.intercept(ParseOkHttpClient.java:214)

and this is Okhttp source code

    public Builder delete(RequestBody body) {
      return method("DELETE", body);
    }

    public Builder delete() {
      return delete(RequestBody.create(null, new byte[0]));
    }

so if invoke delete(),RequestBody is created by okhttp, so can't cast to ParseOkHttpRequestBody.

**Comment by rogerhu** [comment]
could use a test but good to go

**Comment by rogerhu** [comment]
On second thought not sure what this fix does since ParseFile doesn't expose a delete...how does this help?

**Comment by rogerhu** [comment]
Going to close until we have more data on what it's supposed to fix.

**Pull request closed without merging**
