### PR TITLE
Replace deprecated

### PR DESCRIPTION
**Pull request by daisuke-nomura**
Use new `bolts.TaskCompletionSource`.

### CODE REVIEW

**Comment by grantland** [comment]
Looks good! Would you mind squashing your commits?

**Comment by daisuke-nomura** [comment]
No problem.

**Comment by grantland** [comment]
I'm not sure if you attempted this or not, but if you could squash your commits into a single commit we can merge this in. Thanks!

**Comment by grantland** [comment]
@daisuke-nomura just wondering if you're able to squash these two commits still?

**Comment by daisuke-nomura** [comment]
@grantland Sorry for delay.

**Comment by daisuke-nomura** [comment]
I'll fix this.

**Comment by grantland** [comment]
Still two commits, mind squashing again?

**Comment by daisuke-nomura** [comment]
completed.

**Comment by grantland** [comment]
thanks!

**Pull request merged**
